---
title: "Tables"
author: "Miguel ?ngel Armengol de la Hoz"
output:
  html_document:
    toc: true
    theme: united
---


```{r setup, include=FALSE}
#load the data
#load("C:/BIG FILES/Phenotyping/HemodynamicProjectsDatasetFeb18.RData")
```


```{r}
library(tableone)
library(magrittr)
library(officer)
library(xlsx)
```



# Table 1

```{r}
write.csv(table_df, 'Final_dataset.csv',row.names = F)
listVarstab1<-c("patientunitstayid", "age_fixed", "gender", "weight", "height", "BMI", "BMI_group", "unitType", "body_surface_area", "apachescore", "unabridgedunitlos", "unabridgedhosplos", "unabridgedactualventdays", "first_hct_6hrs", "mean_hct_24_36hrs", "AKIstage", "delta_sofa", "delta_sofa_bin", "actualhospitalmortality", "HospitalLOS", "totalFluid")

catVars<-c("gender", "actualicumortality", "actualhospitalmortality", "delta_sofa_bin")

table1 <- CreateTableOne(vars = listVarstab1, data = table_df, factorVars = catVars,testNormal=oneway.test)

table1strat <- CreateTableOne(vars = listVarstab1, data = table_df, factorVars = catVars,testNormal=oneway.test, strata="q_leaking_index")

table1_printed<-as.data.frame(print(table1
                                    #, nonnormal= nonnormal
                                    ))
table1strat_printed<-as.data.frame(print(table1strat
                                         #, nonnormal= nonnormal
                                    ))

table1_final<-cbind(table1_printed,table1strat_printed)

write.csv2(as.data.frame(print(table1_final)), "table1_final.csv")

```
```{r}
# Experimental
listVarstab1<-c("apachescore", "final_charlson_score", "q_leaking_index")

catVars<-c("actualhospitalmortality")

table1 <- CreateTableOne(vars = listVarstab1, data = table_df, factorVars = catVars,testNormal=oneway.test)

table1strat <- CreateTableOne(vars = listVarstab1, data = selected_df, factorVars = catVars,testNormal=oneway.test, strata="actualhospitalmortality")

table1_printed<-as.data.frame(print(table1
                                    #, nonnormal= nonnormal
                                    ))
table1strat_printed<-as.data.frame(print(table1strat
                                         #, nonnormal= nonnormal
                                    ))

table1_final<-cbind(table1_printed,table1strat_printed)

write.csv2(as.data.frame(print(table1_final)), "table2_final.csv")

```


